<option value="AED">AED - UAE Dirham</option>
<option value="AFA">AFA - Afghanistan Afghani</option>
<option value="ALL">ALL - Albanian Lek</option>
<option value="ANG">ANG - Neth Antilles Guilder</option>
<option value="ARS">ARS - Argentine Peso</option>
<option value="AUD">AUD - Australian Dollar</option>
<option value="AWG">AWG - Aruba Florin</option>
<option value="BBD">BBD - Barbados Dollar</option>
<option value="BDT">BDT - Bangladesh Taka</option>
<option value="BHD">BHD - Bahraini Dinar</option>
<option value="BIF">BIF - Burundi Franc</option>
<option value="BMD">BMD - Bermuda Dollar</option>
<option value="BND">BND - Brunei Dollar</option>
<option value="BOB">BOB - Bolivian Boliviano</option>
<option value="BRL">BRL - Brazilian Real</option>
<option value="BSD">BSD - Bahamian Dollar</option>
<option value="BTN">BTN - Bhutan Ngultrum</option>
<option value="BWP">BWP - Botswana Pula</option>
<option value="BZD">BZD - Belize Dollar</option>
<option value="CAD">CAD - Canadian Dollar</option>
<option value="CHF">CHF - Swiss Franc</option>
<option value="CLP">CLP - Chilean Peso</option>
<option value="CNY">CNY - Chinese Yuan</option>
<option value="COP">COP - Colombian Peso</option>
<option value="CRC">CRC - Costa Rica Colon</option>
<option value="CUP">CUP - Cuban Peso</option>
<option value="CVE">CVE - Cape Verde Escudo</option>
<option value="CYP">CYP - Cyprus Pound</option>
<option value="CZK">CZK - Czech Koruna</option>
<option value="DJF">DJF - Dijibouti Franc</option>
<option value="DKK">DKK - Danish Krone</option>
<option value="DOP">DOP - Dominican Peso</option>
<option value="DZD">DZD - Algerian Dinar</option>
<option value="EEK">EEK - Estonian Kroon</option>
<option value="EGP">EGP - Egyptian Pound</option>
<option value="ETB">ETB - Ethiopian Birr</option>
<option value="EUR">EUR - Euro</option>
<option value="FKP">FKP - Falkland Islands Pound</option>
<option value="GBP">GBP - British Pound</option>
<option value="GHC">GHC - Ghanian Cedi</option>
<option value="GIP">GIP - Gibraltar Pound</option>
<option value="GMD">GMD - Gambian Dalasi</option>
<option value="GNF">GNF - Guinea Franc</option>
<option value="GTQ">GTQ - Guatemala Quetzal</option>
<option value="GYD">GYD - Guyana Dollar</option>
<option value="HKD">HKD - Hong Kong Dollar</option>
<option value="HNL">HNL - Honduras Lempira</option>
<option value="HRK">HRK - Croatian Kuna</option>
<option value="HTG">HTG - Haiti Gourde</option>
<option value="HUF">HUF - Hungarian Forint</option>
<option value="IDR">IDR - Indonesian Rupiah</option>
<option value="ILS">ILS - Israeli Shekel</option>
<option value="INR">INR - Indian Rupee</option>
<option value="IQD">IQD - Iraqi Dinar</option>
<option value="ISK">ISK - Iceland Krona</option>
<option value="JMD">JMD - Jamaican Dollar</option>
<option value="JOD">JOD - Jordanian Dinar</option>
<option value="JPY">JPY - Japanese Yen</option>
<option value="KES">KES - Kenyan Shilling</option>
<option value="KHR">KHR - Cambodia Riel</option>
<option value="KMF">KMF - Comoros Franc</option>
<option value="KPW">KPW - North Korean Won</option>
<option value="KRW">KRW - Korean Won</option>
<option value="KWD">KWD - Kuwaiti Dinar</option>
<option value="KYD">KYD - Cayman Islands Dollar</option>
<option value="KZT">KZT - Kazakhstan Tenge</option>
<option value="LAK">LAK - Lao Kip</option>
<option value="LBP">LBP - Lebanese Pound</option>
<option value="LKR">LKR - Sri Lanka Rupee</option>
<option value="LRD">LRD - Liberian Dollar</option>
<option value="LSL">LSL - Lesotho Loti</option>
<option value="LTL">LTL - Lithuanian Lita</option>
<option value="LVL">LVL - Latvian Lat</option>
<option value="LYD">LYD - Libyan Dinar</option>
<option value="MAD">MAD - Moroccan Dirham</option>
<option value="MDL">MDL - Moldovan Leu</option>
<option value="MGF">MGF - Malagasy Franc</option>
<option value="MKD">MKD - Macedonian Denar</option>
<option value="MMK">MMK - Myanmar Kyat</option>
<option value="MNT">MNT - Mongolian Tugrik</option>
<option value="MOP">MOP - Macau Pataca</option>
<option value="MRO">MRO - Mauritania Ougulya</option>
<option value="MTL">MTL - Maltese Lira</option>
<option value="MUR">MUR - Mauritius Rupee</option>
<option value="MVR">MVR - Maldives Rufiyaa</option>
<option value="MWK">MWK - Malawi Kwacha</option>
<option value="MXN">MXN - Mexican Peso</option>
<option value="MYR">MYR - Malaysian Ringgit</option>
<option value="MZM">MZM - Mozambique Metical</option>
<option value="NAD">NAD - Namibian Dollar</option>
<option value="NGN">NGN - Nigerian Naira</option>
<option value="NIO">NIO - Nicaragua Cordoba</option>
<option value="NOK">NOK - Norwegian Krone</option>
<option value="NPR">NPR - Nepalese Rupee</option>
<option value="NZD">NZD - New Zealand Dollar</option>
<option value="OMR">OMR - Omani Rial</option>
<option value="PAB">PAB - Panama Balboa</option>
<option value="PEN">PEN - Peruvian Nuevo Sol</option>
<option value="PGK">PGK - Papua New Guinea Kina</option>
<option value="PHP">PHP - Philippine Peso</option>
<option value="PKR">PKR - Pakistani Rupee</option>
<option value="PLN">PLN - Polish Zloty</option>
<option value="PYG">PYG - Paraguayan Guarani</option>
<option value="QAR">QAR - Qatar Rial</option>
<option value="ROL">ROL - Romanian Leu</option>
<option value="RUB">RUB - Russian Rouble</option>
<option value="SAR">SAR - Saudi Arabian Riyal</option>
<option value="SBD">SBD - Solomon Islands Dollar</option>
<option value="SCR">SCR - Seychelles Rupee</option>
<option value="SDD">SDD - Sudanese Dinar</option>
<option value="SEK">SEK - Swedish Krona</option>
<option value="SGD">SGD - Singapore Dollar</option>
<option value="SHP">SHP - St Helena Pound</option>
<option value="SIT">SIT - Slovenian Tolar</option>
<option value="SKK">SKK - Slovak Koruna</option>
<option value="SLL">SLL - Sierra Leone Leone</option>
<option value="SOS">SOS - Somali Shilling</option>
<option value="SRG">SRG - Surinam Guilder</option>
<option value="STD">STD - Sao Tome Dobra</option>
<option value="SVC">SVC - El Salvador Colon</option>
<option value="SYP">SYP - Syrian Pound</option>
<option value="SZL">SZL - Swaziland Lilageni</option>
<option value="THB">THB - Thai Baht</option>
<option value="TND">TND - Tunisian Dinar</option>
<option value="TOP">TOP - Tonga Pa'anga</option>
<option value="TRL">TRL - Turkish Lira</option>
<option value="TRY">TRY - Turkey Lira</option>
<option value="TTD">TTD - Trinidad&amp;Tobago Dollar</option>
<option value="TWD">TWD - Taiwan Dollar</option>
<option value="TZS">TZS - Tanzanian Shilling</option>
<option value="UAH">UAH - Ukraine Hryvnia</option>
<option value="UGX">UGX - Ugandan Shilling</option>
<option value="USD">USD - U.S. Dollar</option>
<option value="UYU">UYU - Uruguayan New Peso</option>
<option value="VEB">VEB - Venezuelan Bolivar</option>
<option value="VND">VND - Vietnam Dong</option>
<option value="VUV">VUV - Vanuatu Vatu</option>
<option value="WST">WST - Samoa Tala</option>
<option value="XAF">XAF - CFA Franc (BEAC)</option>
<option value="XAG">XAG - Silver Ounces</option>
<option value="XAU">XAU - Gold Ounces</option>
<option value="XCD">XCD - East Caribbean Dollar</option>
<option value="XOF">XOF - CFA Franc (BCEAO)</option>
<option value="XPD">XPD - Palladium Ounces</option>
<option value="XPF">XPF - Pacific Franc</option>
<option value="XPT">XPT - Platinum Ounces</option>
<option value="YER">YER - Yemen Riyal</option>
<option value="YUM">YUM - Yugoslav Dinar</option>
<option value="ZAR">ZAR - South African Rand</option>
<option value="ZMK">ZMK - Zambian Kwacha</option>
<option value="ZWD">ZWD - Zimbabwe Dollar</option>
